DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 20
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]
  # TRANSFORMS: ["random_resized_crop", "random_flip", "normalize","colorjitter","randomgrayscale","gaussian_blur"]
  # COLORJITTER_B: 0.4
  # COLORJITTER_C: 0.4
  # COLORJITTER_S: 0.4
  # RGS_P: 0.2
  # GB_K: 3
  # GB_P: 0.5

OPTIM:
  NAME: "sgd"
  LR: 0.002
  MAX_EPOCH: 100
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 5

TEST:
  NO_TEST: False
  FINAL_MODEL: "best_val"

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"
AL:
  NAME: "entropy"
  SAMPLE_SAVE_PATH: "Flowers102/acil/entropy/R_5/SEED1"
  ROUND: 5
CL:
  NAME: "LP-DiF"
  USE_PSEUDO: False